### PR TITLE
features/75-WITec-unittest

### LINKED ISSUE #75: Improve WITec unit tests
In addition to current unit tests, add template #55 for these functions:

- [ ] read_dat_WITec
- [ ] read_txt_WITec
- [ ] read_txt_WITec_Graph
- [ ] read_txt_WITec_TrueMatch

(the current test should remain in the files)

### PR DESCRIPTION
**Pull request by sangttruong**
Resolve #75

### CODE REVIEW

**Comment by GegznaV** [comment]
@sangttruong, were the old unit tests removed and only new ones based on #55 added? Or both old and new unit tests are kept in this PR?

**Review by GegznaV — CHANGES_REQUESTED** [review]
We must keep both old and new unit tests. Just for the old ones, we must use correct paths to files by using `system.file()` function.

THese files, that were in `tar` archive, must also be present in `inst/extdata` directory.

**Comment by GegznaV** [comment]
@sangttruong wrote:


> Here is the block that I use to read the file
> 
> ```r
>   header <- system.file(
>     "extdata",
>     "txt.Witec/nofilename_Header.txt",
>     package = "hySpc.read.txt"
>   )
>   
>   filex <- system.file(
>     "extdata",
>     "txt.Witec/nofilename_X-Axis.txt",
>     package = "hySpc.read.txt"
>   )
> 
>   filey <- system.file(
>     "extdata",
>     "txt.Witec/nofilename_Y-Axis.txt",
>     package = "hySpc.read.txt"
>   )
>   expect_silent(spc <- read_txt_WITec_Graph(header, filex, filey))
> ```
> 
> It keeps throwing this cryptic error: Error in lapply(tmp, as.numeric) :
>   invalid multibyte string at '<fc><be><8d><96><88><bc>m'
> 
> It's the last commit on reading `.txt` if you would like to take a look. The old unit test (which I commented out at the bottom doesn't return an error)

I do not have time to look into this now. @cbeleites, can you help?

**Review by bryanhanson — APPROVED** [review]
Everything works, all comments addressed.

**Pull request merged**
