### PR TITLE
Update drat workflow

### PR DESCRIPTION
**Pull request by GegznaV**
Mainly style related changes in **drat** workflow file. Some lines were moved to a different step. One redundant step was removed.

### CODE REVIEW

**Review by bryanhanson — COMMENTED** [review]
This is not redundant.  The needed `.tar.gz` is not in the directory that will be pushed.  To verify you'll need to set the token back to `HYSPC_EO_TOKEN` or it won't authenticate.

**Review by bryanhanson — APPROVED** [review]

**Review by bryanhanson — APPROVED** [review]
Nice idea.  Thanks.

**Review by bryanhanson — APPROVED** [review]

**Comment by GegznaV** [comment]
I'll recheck that a bit later.

**Comment by bryanhanson** [comment]
You were correct: the forced add of `.tar.gz` was no longer needed.

**Review by bryanhanson — APPROVED** [review]

**Review by bryanhanson — APPROVED** [review]

**Review by bryanhanson — APPROVED** [review]

**Review by bryanhanson — APPROVED** [review]

**Review by bryanhanson — COMMENTED** [review]
I do think this is required.  The `add -f` is not.

**Comment by bryanhanson** [comment]
Alright, I'm a little lost with this pull review.  Github is showing me suggested edits that I can't understand -- the formatting is odd and I can't tell where Github thinks the conflict is.  If it's too mangled I can re-create the edits for the most part separately.

**Comment by GegznaV** [comment]
Leave the conflicts for me.

I have a very good program called Meld (if you try google it, keywords are
"meld merge") that I use for solvong Git conflicts. It works on Windows and
I'm not sure if it is available on Mac.

2020 rugp. 17, pr 22:19, Bryan Hanson <notifications@github.com> rašė:

**Comment by GegznaV** [comment]
> 
> 
> I do think this is required. The `add -f` is not.

`add -f` is needed when we want to add a new git-ignored file.

**Comment by GegznaV** [comment]
>  where Github thinks the conflict is.

I've solved the conflicts.

**Comment by bryanhanson** [comment]
Thank you!

**Pull request merged**
